### ISSUE TITLE
NavigationStateUtils的实现？

### ISSUE THREAD

**Issue by walter211** [imWildCat/wetoo#1]
NavigationStateUtils在哪啊？

**Comment by MikeChongCan** [comment]
你在哪里看到的 'NavigationStateUtils'?

**Comment by walter211** [comment]
src/reducers/navigations.js里面

**Comment by MikeChongCan** [comment]
`NavigationStateUtils` 应该是 react native 的 hack，`@provideModule`: https://github.com/facebook/react-native/blob/master/Libraries/NavigationExperimental/NavigationStateUtils.js

貌似本项目不用这个了，用封装过的 `react-native-router-flux`，但是现在用 `exNavigation` 比较推荐

**Comment by MikeChongCan** [comment]
I close this issue because of no response.
Please feel free to reopen it if you have any further questions.

**Comment by walter211** [comment]
知道了，多谢！
